spring: 
  encrypt: 
    key: abcdef0123456789
    debug: false
  profiles: 
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?characterEncoding=utf8&useSSL=true
    username: root
    password: dengqw
redisson: 
  lock: 
    server: 
      address: 127.0.0.1:6379
      type: standalone 
redis: 
  lock: 
    cron: 0/5 * * * * ?
    
logging: 
  pattern: 
    console: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
    file: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
  file: d:/log/redis-distributed-lock-demo-spring/console.log
  level: 
    com.kingdee.abc: INFO


